### ISSUE TITLE
Level 1 needs to be completed

### ISSUE THREAD

**Issue by Toltar** [HarambeStudios/Project-Spacetime#20]
Relies on issues:
#29  
#24  
#26

## TODO
- [x] Level Asset Needs to be complete
- [x] #29 and #24 Needs to be in there
- [x] #26 needs to be implemented
- [x] Player can hit the switch if they are of the other universe
