### ISSUE TITLE
Level 2 needs to be completed

### ISSUE THREAD

**Issue by Toltar** [HarambeStudios/Project-Spacetime#21]
Relies on issues: #29  #24  #26 #23 #27 

## TODO
- [x] Level Asset Needs to be complete
- [x] #29 and #24 needs to be in there
- [x] #23 and #27 needs to be done
- [x] #26 needs to be implemented
- [x] Player can hit the switch if they are of the other universe

**Comment by samplenr** [comment]
Did a quick mock up for a level for lvl 2, hazards are on map (holes and lava) but cant get the triggers to function properly to kill the player. Also still need to set the trigger to open the door. The door is rendered on a layer separate from the wall it is on, so that part should be fairly simple.  Player interacts with walls properly however.

**Comment by samplenr** [comment]
Fixed the collisions with the hazards, they now properly kill the character if he stumbles into them.

**Comment by samplenr** [comment]
lvl2 branch now has switch that destroys block on door and shows door

**Comment by Toltar** [comment]
Door switch works! It is able to select which player the switch can be activated by,

![doorswitchworks2](https://cloud.githubusercontent.com/assets/6003536/19421623/1b1aa42a-93cb-11e6-8a6a-cbac3223fa7f.gif)
